version: '3.1'

services:
  
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: db_test
    volumes: 
      - /var/lib/mysql
    ports:
      - 8080:8080

  db2:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_test_2
      POSTGRES_USER: root
    volumes: 
      - /var/lib/postgresql/data
    ports:
      - 5432:5432


    